"""create tender_documents table

Revision ID: 274ed1cb1558
Revises: d54652329f0b
Create Date: 2026-02-19 20:47:39.172365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '274ed1cb1558'
down_revision: Union[str, None] = 'd54652329f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'filename', name='uq_tender_document_filename')
    )
    op.alter_column('notices', 'tender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notices_tender_id'), table_name='notices')
    op.drop_constraint(op.f('notices_notice_id_key'), 'notices', type_='unique')
    op.create_unique_constraint('uq_source_notice', 'notices', ['source', 'notice_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_source_notice', 'notices', type_='unique')
    op.create_unique_constraint(op.f('notices_notice_id_key'), 'notices', ['notice_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_notices_tender_id'), 'notices', ['tender_id'], unique=False)
    op.alter_column('notices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notices', 'tender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('tender_documents')
    # ### end Alembic commands ###
