"""create_notices_table

Revision ID: c2f5d73f60c9
Revises: 
Create Date: 2026-02-17 22:53:00.570106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2f5d73f60c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Text(), nullable=True),
    sa.Column('f_1_1', sa.Text(), nullable=True, comment='Rola zamawiającego'),
    sa.Column('f_1_2', sa.Text(), nullable=True, comment='Nazwa zamawiającego'),
    sa.Column('f_1_5_1', sa.Text(), nullable=True, comment='Ulica'),
    sa.Column('f_1_5_2', sa.Text(), nullable=True, comment='Miejscowość'),
    sa.Column('f_1_5_3', sa.Text(), nullable=True, comment='Kod pocztowy'),
    sa.Column('f_1_5_4', sa.Text(), nullable=True, comment='Województwo'),
    sa.Column('f_1_5_5', sa.Text(), nullable=True, comment='Kraj'),
    #sa.Column('f_1_5_6', sa.Text(), nullable=True, comment='Lokalizacja NUTS 3'),
    sa.Column('f_1_5_9', sa.Text(), nullable=True, comment='Email'),
    sa.Column('f_1_5_10', sa.Text(), nullable=True, comment='Strona www'),
    sa.Column('f_1_6', sa.Text(), nullable=True, comment='Rodzaj zamawiającego'),
    sa.Column('f_1_7', sa.Text(), nullable=True, comment='Przedmiot działalności'),
    sa.Column('f_2_1', sa.Text(), nullable=True, comment='Ogłoszenie dotyczy'),
    sa.Column('f_2_2', sa.Text(), nullable=True, comment='Usługi społeczne'),
    sa.Column('f_2_3', sa.Text(), nullable=True, comment='Nazwa zamówienia'),
    sa.Column('f_2_4', sa.Text(), nullable=True, comment='Identyfikator postępowania'),
    sa.Column('f_2_5', sa.Text(), nullable=True, comment='Numer ogłoszenia'),
    sa.Column('f_2_6', sa.Text(), nullable=True, comment='Wersja ogłoszenia'),
    sa.Column('f_2_7', sa.Text(), nullable=True, comment='Data ogłoszenia'),
    sa.Column('f_2_8', sa.Text(), nullable=True, comment='Ujęte w planie'),
    sa.Column('f_2_11', sa.Text(), nullable=True, comment='Art. 94'),
    sa.Column('f_2_14', sa.Text(), nullable=True, comment='Projekt UE'),
    sa.Column('f_2_16', sa.Text(), nullable=True, comment='Tryb udzielenia'),
    sa.Column('f_3_1', sa.Text(), nullable=True, comment='Adres strony postępowania'),
    sa.Column('f_3_2', sa.Text(), nullable=True, comment='Zastrzega dostęp'),
    sa.Column('f_3_4', sa.Text(), nullable=True, comment='Komunikacja elektroniczna'),
    sa.Column('f_3_5', sa.Text(), nullable=True, comment='Środki komunikacji'),
    sa.Column('f_3_6', sa.Text(), nullable=True, comment='Wymagania techniczne'),
    sa.Column('f_3_8', sa.Text(), nullable=True, comment='Narzędzia BIM'),
    sa.Column('f_3_12', sa.Text(), nullable=True, comment='Katalog elektroniczny'),
    sa.Column('f_3_14', sa.Text(), nullable=True, comment='Języki'),
    #sa.Column('f_3_15', sa.Text(), nullable=True, comment='RODO'),
    sa.Column('f_4_1_1', sa.Text(), nullable=True, comment='Konsultacje rynkowe'),
    sa.Column('f_4_1_2', sa.Text(), nullable=True, comment='Numer referencyjny'),
    sa.Column('f_4_1_3', sa.Text(), nullable=True, comment='Rodzaj zamówienia'),
    sa.Column('f_4_1_4', sa.Text(), nullable=True, comment='Zamówienie w częściach'),
    sa.Column('f_4_1_8', sa.Text(), nullable=True, comment='Oferty częściowe'),
    sa.Column('f_4_1_13', sa.Text(), nullable=True, comment='Aspekty społeczne'),
    sa.Column('f_4_2_2', sa.Text(), nullable=True, comment='Krótki opis'),
    sa.Column('f_4_2_6', sa.Text(), nullable=True, comment='Główny kod CPV'),
    sa.Column('f_4_2_8', sa.Text(), nullable=True, comment='Opcje'),
    sa.Column('f_4_2_10', sa.Text(), nullable=True, comment='Okres realizacji'),
    sa.Column('f_4_2_11', sa.Text(), nullable=True, comment='Wznowienia'),
    sa.Column('f_4_2_13', sa.Text(), nullable=True, comment='Zamówienia podobne'),
    sa.Column('f_4_3', sa.Text(), nullable=True, comment='Kryteria oceny ofert'),
    sa.Column('f_4_3_2', sa.Text(), nullable=True, comment='Sposób określania wagi'),
    sa.Column('f_4_3_3', sa.Text(), nullable=True, comment='Stosowane kryteria'),
    sa.Column('f_4_3_5', sa.Text(), nullable=True, comment='Nazwa kryterium'),
    sa.Column('f_4_3_6', sa.Text(), nullable=True, comment='Waga'),
    sa.Column('f_4_3_10', sa.Text(), nullable=True, comment='Aspekty społeczne w kryteriach'),
    sa.Column('f_5_1', sa.Text(), nullable=True, comment='Fakultatywne wykluczenia'),
    sa.Column('f_5_3', sa.Text(), nullable=True, comment='Warunki udziału'),
    sa.Column('f_5_5', sa.Text(), nullable=True, comment='Oświadczenie art.125'),
    sa.Column('f_6_1', sa.Text(), nullable=True, comment='Oferty wariantowe'),
    sa.Column('f_6_3', sa.Text(), nullable=True, comment='Aukcja elektroniczna'),
    sa.Column('f_6_4', sa.Text(), nullable=True, comment='Wadium'),
    sa.Column('f_6_5', sa.Text(), nullable=True, comment='Zabezpieczenie'),
    sa.Column('f_6_6', sa.Text(), nullable=True, comment='Wykonawcy wspólni'),
    sa.Column('f_6_7', sa.Text(), nullable=True, comment='Unieważnienie'),
    sa.Column('f_7_1', sa.Text(), nullable=True, comment='Zaliczki'),
    sa.Column('f_7_3', sa.Text(), nullable=True, comment='Zmiany umowy'),
    sa.Column('f_7_4', sa.Text(), nullable=True, comment='Rodzaj zmian'),
    sa.Column('f_7_5', sa.Text(), nullable=True, comment='Aspekty społeczne'),
    sa.Column('f_8_1', sa.Text(), nullable=True, comment='Termin składania'),
    sa.Column('f_8_2', sa.Text(), nullable=True, comment='Miejsce składania'),
    sa.Column('f_8_3', sa.Text(), nullable=True, comment='Termin otwarcia'),
    sa.Column('f_8_4', sa.Text(), nullable=True, comment='Termin związania'),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notices')
    # ### end Alembic commands ###
