version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg15
    container_name: przetargi_db
    environment:
      POSTGRES_USER: przetargi_user
      POSTGRES_PASSWORD: przetargi_password
      POSTGRES_DB: przetargi_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
