"""create_notices_table

Revision ID: c2f5d73f60c9
Revises: 
Create Date: 2026-02-17 22:53:00.570106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2f5d73f60c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('ezamowienia', 'ted', 'platformazakupowa', name='notice_source_type'), nullable=False),
    sa.Column('notice_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notice_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notices')
    # Ręczne usunięcie typu enum
    sa.Enum(name='notice_source_type').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
